export const vehicleInputFields = [
  {
    label: "Area Office",
    type: "text",
    name: "AreaOffice",
    required: true,
  },
  {
    label: "Engine Number",
    type: "text",
    name: "EngineNumber",
    required: true,
  },
  {
    label: "Make",
    type: "text",
    name: "Make",
    required: true,
  },
  {
    label: "Market Value",
    type: "text",
    name: "MarketValue",
    required: true,
  },
  {
    label: "MM Number",
    type: "text",
    name: "MMNumber",
    required: true,
  },
  {
    label: "Model",
    type: "text",
    name: "Model",
    required: true,
  },
  {
    label: "Record Id",
    type: "text",
    name: "RecordId",
    required: true,
  },
  {
    label: "Registration Number",
    type: "text",
    name: "RegistrationNumber",
    required: true,
  },
  {
    label: "Retail Price",
    type: "text",
    name: "RetailPrice",
    required: true,
  },
  {
    label: "Trade Price",
    type: "text",
    name: "TradePrice",
    required: true,
  },
  {
    label: "Transaction Number",
    type: "text",
    name: "TransactionNumber",
    required: true,
  },
  {
    label: "Vehicle Ref",
    type: "text",
    name: "VehicleRef",
    required: true,
  },
  {
    label: "VIN Number",
    type: "text",
    name: "VINNumber",
    required: true,
  },
  {
    label: "WRTYEnd",
    type: "text",
    name: "WRTYEnd",
    required: true,
  },
  {
    label: "WRTYStart",
    type: "text",
    name: "WRTYStart",
    required: true,
  },
  {
    label: "YearModel",
    type: "text",
    name: "YearModel",
    required: true,
  },
  {
    label: "VehicleNumber",
    type: "text",
    name: "VehicleNumber",
    required: true,
  },
];
